spring:
  config:
    import:
      - classpath:config/application-db.properties
      - classpath:config/application-api.properties
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

api:
  server:
    url: ${api.server.url}
mybatis:
  mapper-locations: classpath:/mappers/**/*.xml

logging:
  level:
    org.springframework.web: DEBUG
    com.farm.pedia: DEBUG