spring:
  config:
    import:
      - classpath:config/application-db.properties
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}

  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: farmpedia
      password: 0000

mybatis:
  mapper-locations: classpath:/mappers/user/*.xml


logging:
  level:
    org.springframework.web: DEBUG
    com.farm.pedia: DEBUG