version: '3.7'
services:
  recent-redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: recent-redis
    hostname: recent-redis
    labels:
      - "name=recent-redis"
      - "mode=standalone"
    ports:
        - "6379:6379"